server:
  port: 8888

gif:
  url: https://api.giphy.com/v1/gifs
  api_key: SsZYyPw4gbOeoL8pCOy7pzuCBOeOWEBF

currency:
  url: https://openexchangerates.org/api/historical
  api_key: ffca962a806d48feb2b7e213ff95194f
  base: USD
