server:
  port: 8888

gif:
#  url: https://api.giphy.com/v1/gifs
  url: https://developers.giphy.com/docs/api#quick-start-guide
  api_key: SsZYyPw4gbOeoL8pCOy7pzuCBOeOWEBF

currency:
#  url: https://openexchangerates.org/api/historical
  url: https://docs.openexchangerates.org/
  api_key: ffca962a806d48feb2b7e213ff95194f
  base: USD
