spring:

gif:
  url: https://developers.giphy.com/docs/api#quick-start-guide
  api_key: SsZYyPw4gbOeoL8pCOy7pzuCBOeOWEBF

currency:
  url: https://docs.openexchangerates.org/
  api_key: ffca962a806d48feb2b7e213ff95194f
  base: USD
